body:
  - type: markdown
    attributes:
      value: "### ❓ 질문 내용을 작성해주세요."
  - type: textarea
    id: question
    attributes:
      label: "질문"
      description: "질문을 자세히 설명해주세요."
      placeholder: "예: React에서 useEffect를 어떻게 사용하나요?"
    validations:
      required: true
  - type: dropdown
    id: related_topic
    attributes:
      label: "관련 주제"
      description: "어떤 주제와 관련된 질문인가요?"
      options:
        - "React"
        - "Vue"
        - "JavaScript"
        - "TypeScript"
        - "기타"
    validations:
      required: true
